### ISSUE TITLE
Suggestion: don't numbering the section in the actual documentation

### ISSUE THREAD

**Issue by ypsun-umd** [umd-lhcb/brkoutbrd_qa_doc#1]
Great work Jorge! 

Still I claim that it would be better if we don't manually numbering each section, subsection, etc. Because I will set up this project to use Travis CI to automatically generate a pdf file with `pandoc`, which then calls `LaTeX` to generate a pretty pdf.

**Comment by LegyPlegy** [comment]
Sounds good to me. I will edit the .md accordingly.
