### ISSUE TITLE
Time to generate a pdf file

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/brkoutbrd_qa_doc#3]
I think now there's enough content to generate a pdf file using the following route:
```
markdown - pandoc -> (latex) - choice of tex engine -> pdf
```

With the help of Travis CI, we can do that without install anything locally. I'll start the process.

**Comment by SummerLeaves** [comment]
@SummerLeaves

**Comment by SummerLeaves** [comment]
@SummerLeaves Test

**Comment by SummerLeaves** [comment]
@SummerLeaves Test2

**Comment by yipengsun** [comment]
There are more important things to do. Won't implement this for now.
