### ISSUE TITLE
Board Count

### ISSUE THREAD

**Issue by wcparker** [umd-lhcb/brkoutbrd_qa_doc#4]
Hi Jorge and Raymond,

  It would be useful to have an up-to-date count of how many of each type of board you have produced.  Please add it to the documentation when you have time.

Thanks,

Will

**Comment by SummerLeaves** [comment]
@wcparker Testing the issue notification

**Comment by ypsun-umd** [comment]
@SummerLeaves @LegyPlegy Please provide some follow-up information once you finish counting. Thanks.

**Comment by ypsun-umd** [comment]
@SummerLeaves I think you should put your 'Board Count and Objective' here, instead of creating a new file. Because this is not a document, it is a check list.

**Comment by ypsun-umd** [comment]
- Total Boards: ?
- Input Boards: (Needs to be counted. Some in basement.)
- Output Boards: 17/30 (At 30 check in with Will)
  - Due Date: 10/30
  - Would be good to have at least 30 by the end of October -Will
- Power Cables: 2/12
  - Due Date: (Check in with Brian)

- Input Boards Installed: ?/52
  - It would be good if you can **actually** install the 3D-printed brackets -Yipeng
  
## Raymond (@SummerLeaves)
- 11 Output Boards (GOAL: 15) 
- 0 Power Cables 

## Jorge (@LegyPlegy)
- 6 Output Boards (GOAL: 15)
- 2 Power Cables

## TO DO: 
- [ ]  We need to mark the boards we make for quality control purposes.
- [ ] We need to make documentation for the Output Boards and Power Cables

**Comment by SummerLeaves** [comment]
I thought it'd be better to leave it as a separate file since 
- It doesn't really having anything to do with the QA doc on the input board construction, and
- Is a more general file that we're editing to keep track of the completed boards. 

I can put it in the QA doc for now, and if you still think it's a better idea.
Thanks for the feedback!

@ypsun-umd

**Comment by ypsun-umd** [comment]
Nah, I was saying that we should use this issue as the board-counting tracking; create no new files
